apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigdemoapi-deployment
  labels: 
    app: gigapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gigapi
  template:
    metadata:
      labels:
        app: gigapi
    spec:
      containers:
      - name: gigapi
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-url      

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: gigapi
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30002
