apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigdemodb-deployment
  labels: 
    app: gigdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigdb
  template:
    metadata:
      labels:
        app: gigdb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: gigdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
